version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kfk
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    - "9999:9999"
    expose:
    - "9093"
    environment:
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.1.35:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.1.35 -Dcom.sun.management.jmxremote.rmi.port=9999"
        JMX_PORT: 9999
        KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-eagle:
    image: gui66497/kafka_eagle2
    container_name: ke
    ports:
      - "8048:8048"
    environment:
      ZKSERVER: "zookeeper:2181"
    volumes:
      - ./system-config.properties:/kafka-eagle/conf/system-config.properties
      - ./logs:/kafka-eagle/logs
