version: '3'
services:
  kafka-eagle:
    image: kafka-eagle:v1.0
    container_name: kfk-eagle
    restart: always
    ports:
      - "8048:8048"
    environment:
      ZKSERVER: "z-2.m22-kafka-lottery.0k10h8.c4.kafka.ap-southeast-1.amazonaws.com:2181,z-3.m22-kafka-lottery.0k10h8.c4.kafka.ap-southeast-1.amazonaws.com:2181,z-1.m22-kafka-lottery.0k10h8.c4.kafka.ap-southeast-1.amazonaws.com:2181"
    volumes:
      #- ./config/eagle.properties:/kafka-eagle/bin/system-config.properties
      - ./config/system-config.properties:/kafka-eagle/conf/system-config.properties
      - ./logs:/kafka-eagle/logs
